### ISSUE TITLE
Automatic creation of Pulumi.yaml file

### ISSUE THREAD

**Issue by kkiani** [DataChefHQ/damavand#12]
# Description:
We need to establish a solution for creating and managing the `Pulumi.yaml` file, which is crucial for configuring Pulumi deployments. This file is required by Pulumi during the execution of `pulumi up` when users of Damavan wants to deploy the infrastructures.

# Tasks:

- [ ] Develop a standard template for the `Pulumi.yaml` file.
- [ ] Investigate and integrate a community tool to automate the generation of the `Pulumi.yaml` file based on project requirements.
- [ ] Document the process for creating and updating the `Pulumi.yaml` file.

# Acceptance Criteria:

- [ ] A standard `Pulumi.yaml` template is created and tested.
- [ ] The chosen tool is already being used in other parts or is well-known and widely being used by the community.
- [ ] Documentation is provided for using and updating the `Pulumi.yaml` file.
