### ISSUE TITLE
Add Support for Azure Blob Storage in Object Storage Application

### ISSUE THREAD

**Issue by kkiani** [DataChefHQ/damavand#13]
# Description:
Enhance the blog storage application by adding support for Azure Blob Storage. This will enable the application to use Azure Blob Storage for storing and managing blog content, such as images, documents, and other media.

# Tasks

- [ ] Implement Pulumi templates for deploying Azure Blob Storage and creating a Pulumi Component.
- [ ] Implementing Azure APIs support for uploading, downloading, removing, listing, etc. for Azure blob storage.

# Acceptance Criteria:

- [ ] Successfully create a Blob storage on Azure with Pulumi.
- [ ] Can perform create, delete, update, list, etc. actions on the provisioned blob storage.
